// --- MODAL SELECTORS & LOGIC ---
const authModal = document.getElementById('authModal');
const openAuthBtn = document.getElementById('openAuthBtn');
const closeBtn = document.querySelector('.close-btn');
const loginTab = document.getElementById('loginTab');
const signupTab = document.getElementById('signupTab');
const loginForm = document.getElementById('loginForm');
const signupForm = document.getElementById('signupForm');

openAuthBtn.addEventListener('click', () => authModal.style.display = 'flex');
closeBtn.addEventListener('click', () => authModal.style.display = 'none');
window.addEventListener('click', (e) => { if (e.target === authModal) authModal.style.display = 'none'; });

loginTab.addEventListener('click', () => {
    loginTab.classList.add('active'); signupTab.classList.remove('active');
    loginForm.classList.remove('hidden'); signupForm.classList.add('hidden');
});

signupTab.addEventListener('click', () => {
    signupTab.classList.add('active'); loginTab.classList.remove('active');
    signupForm.classList.remove('hidden'); loginForm.classList.add('hidden');
});

loginForm.addEventListener('submit', (e) => {
    e.preventDefault(); alert('Logged in successfully to Khadmeen Wiser portal!');
    authModal.style.display = 'none';
});

signupForm.addEventListener('submit', (e) => {
    e.preventDefault(); alert('Account created successfully!');
    authModal.style.display = 'none';
});


// --- NEW COMPONENT LOGIC ---

// 1. Booking Ticket Processing Engine
const bookingForm = document.getElementById('bookingForm');

bookingForm.addEventListener('submit', (e) => {
    e.preventDefault();
    
    const clientName = document.getElementById('clientName').value;
    const device = document.getElementById('deviceType').value;
    
    // Generate an automatic random ticket tracking code (e.g. KW-3849)
    const randomTicketNumber = Math.floor(1000 + Math.random() * 9000);
    const generatedTicketId = `KW-${randomTicketNumber}`;

    alert(`Thank you, ${clientName}!\nYour ticket has been submitted.\n\nYour Track ID is: ${generatedTicketId}\nUse this ID in our tracking bar above to monitor repair status.`);
    
    // Auto-fill the ticket ID inside the tracker for easy testing
    document.getElementById('ticketInput').value = generatedTicketId;
    bookingForm.reset();
});


// 2. Client Repair Ticket Tracker Engine
const trackBtn = document.getElementById('trackBtn');
const ticketInput = document.getElementById('ticketInput');
const trackerVisual = document.getElementById('trackerVisual');
const trackerMessage = document.getElementById('trackerMessage');

// Mock tickets database schema to simulate status shifts
const mockTicketsDatabase = {
    "KW-1001": { currentStep: 1, text: "Status: Device safely checked into our queue. Awaiting diagnostic engineer." },
    "KW-1002": { currentStep: 2, text: "Status: Diagnostics running. Testing system components and log files." },
    "KW-1003": { currentStep: 3, text: "Status: Currently on the workbench. Repairs & part installations underway." },
    "KW-1004": { currentStep: 4, text: "Status: Fully repaired, cleaned, and verified. Ready for client collection!" }
};

trackBtn.addEventListener('click', () => {
    const rawTicketValue = ticketInput.value.trim().toUpperCase();

    if (!rawTicketValue) {
        alert("Please enter a valid tracking Ticket ID code.");
        return;
    }

    trackerVisual.classList.remove('hidden');
    
    // Reset all status UI steps safely
    for(let i = 1; i <= 4; i++) {
        document.getElementById(`step${i}`).classList.remove('active', 'completed');
    }

    // Check if ticket exists in our mock database dictionary
    if (mockTicketsDatabase[rawTicketValue]) {
        const ticketData = mockTicketsDatabase[rawTicketValue];
        updateTrackerUI(ticketData.currentStep, ticketData.text);
    } else {
        // If it's a dynamic ticket generated by booking form, set it to "Received" status step by default
        updateTrackerUI(1, `Status: Ticket active. Device received at our Khadmeen Wiser center.`);
    }
});

function updateTrackerUI(activeStep, statusText) {
    trackerMessage.innerText = statusText;
    
    for (let i = 1; i <= 4; i++) {
        const stepElement = document.getElementById(`step${i}`);
        if (i < activeStep) {
            stepElement.classList.add('completed');
        } else if (i === activeStep) {
            stepElement.classList.add('active');
        }
    }
}
